In [1]:
matrix=[1,2,3]


In [2]:
matrix

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr=np.array(matrix)

In [5]:
arr

array([1, 2, 3])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
#this creates an identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.82510867, 0.13162642, 0.99895125, 0.49012568, 0.06619308])

In [16]:
np.random.rand(5,5)

array([[0.93015536, 0.6340824 , 0.65122276, 0.35530558, 0.081133  ],
       [0.08487243, 0.09545383, 0.88352847, 0.33789333, 0.20038787],
       [0.25190428, 0.44134516, 0.31822771, 0.54250178, 0.89115199],
       [0.78404348, 0.18277971, 0.18117791, 0.07213135, 0.01628459],
       [0.59298204, 0.8271124 , 0.68897633, 0.67024038, 0.31938687]])

In [17]:
#the above gave us random values between 0 to 1
#the below code will give us random values wrt normal distribution

np.random.randn(5)

array([-1.07035018,  0.86560668,  0.53347011,  0.15776553, -0.03127841])

In [18]:
#this works like the sample function in Rstudio

np.random.randint(1,100,10)

array([82, 33, 95, 66, 54, 57, 67, 50, 61, 19])

In [19]:
arr=np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr=np.random.randint(0,50,10)

In [22]:
ranarr

array([ 9,  0, 38,  6,  2, 28,  5,  0, 47, 30])

In [25]:
#the below code reshapes the array as a matrix
#keep in mind the number of rows x number of columns = no. of elements

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

47

In [28]:
ranarr.min()

0

In [29]:
#The below code returns back the index value of the max/min value in the array

ranarr.argmin()

1

In [32]:
#returns the type of values in arr

arr.dtype

dtype('int32')

In [34]:
#The below code helps us directly use randint without typing the whole np.random.randit out

from numpy.random import randint

randint(2,10)

9